### ISSUE TITLE
test assumes mpirun accepts -N option

### ISSUE THREAD

**Issue by rhaas80** [ECP-VeloC/redset#20]
In

https://github.com/ECP-VeloC/redset/blob/638c6501a6ce02c6fdf95e72c92b1c8a40e5cacb/test/CMakeLists.txt#L11

the test assume that 

```
${MPIEXEC} ${MPIEXEC_NUMPROC_FLAG} 2 -N2 ./redset_test
```

is generically valid, however `-N` is not a documented option of mpiexec and seems to mostly be an `srun` or so option to specify how many ranks per node to use. It fails eg if `RESOURCE_MANAGER=NONE` is used and OpenMPI is the mpi stack.

**Comment by CamStan** [comment]
#36 and #37 should have resolved this.

**Comment by CamStan** [comment]
#36 and #37 should have resolved this.
